fail_fast: true
stages: [commit, push, manual]
pass_filenames: false
always_run: true

repos:
- repo: local
  hooks:
    - id: pytest
      language: system
      entry: pytest .
      types: [python]

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
    - id: isort
      exclude: '^.*migrations.*$'

- repo: https://github.com/ambv/black
  rev: 21.12b0
  hooks:
    - id: black
      args: [--line-length=119]
      exclude: '^.*migrations.*$'

- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-json
    - id: pretty-format-json
    - id: debug-statements
    - id: flake8
      exclude: '^.*migrations.*$'
      additional_dependencies: [
        'flake8-blind-except',
        'flake8-comprehensions',
        'flake8-pep3101',
      ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.770
  hooks:
    - id: mypy
      args: [--follow-imports=silent, --ignore-missing-imports]
